libzwerg/selector: Explicitly show an empty selector
Fix dumping of an empty selector such that instead of this:

    $ dwgrep -e 'foo'
    Error: `foo' expects T_ATTR, or T_ELFSYM near TOS.  Actual profile is .

... the following is shown:

    $ dwgrep -e 'foo'
    Error: `foo' expects T_ATTR, or T_ELFSYM near TOS.  Actual profile is [empty].